# This is a TOML config file to configurate connection to VM.
# For more information, see https://github.com/toml-lang/toml

##### main base config options #####

# VM network address to connect.
vm_address = "tcp://127.0.0.1:50051"

# VM data server listen address.
vm_data_listen = "tcp://127.0.0.1:50052"

# VM retry settings.

## Retry max attempts.
## Default is 0 - infinity attempts.
vm_retry_max_attempts = 0

## Request timeout per attempt in ms.
## Default is 0 - infinite (no timeout).
vm_retry_req_timeout_ms = 0
