// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: dfinance/staker/genesis.proto

package types

import (
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	_ "github.com/regen-network/cosmos-proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type GenesisState struct {
	// Keeper param values
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params" yaml:"params"`
	// The latest unique call ID
	LastCallId *github_com_cosmos_cosmos_sdk_types.Uint `protobuf:"bytes,2,opt,name=last_call_id,json=lastCallId,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Uint" json:"last_call_id,omitempty" yaml:"last_call_id"`
	// Historical call entries
	Calls []Call `protobuf:"bytes,3,rep,name=calls,proto3" json:"calls" yaml:"calls"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_25ef71ee7c6bdcc9, []int{0}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

// Params keeps keeper parameters (which might be changed via Gov).
type Params struct {
	// Admin account addresses
	Nominees []string `protobuf:"bytes,1,rep,name=nominees,proto3" json:"nominees,omitempty" yaml:"nominees"`
}

func (m *Params) Reset()      { *m = Params{} }
func (*Params) ProtoMessage() {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_25ef71ee7c6bdcc9, []int{1}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetNominees() []string {
	if m != nil {
		return m.Nominees
	}
	return nil
}

func init() {
	proto.RegisterType((*GenesisState)(nil), "dfinance.staker.v1beta1.GenesisState")
	proto.RegisterType((*Params)(nil), "dfinance.staker.v1beta1.Params")
}

func init() { proto.RegisterFile("dfinance/staker/genesis.proto", fileDescriptor_25ef71ee7c6bdcc9) }

var fileDescriptor_25ef71ee7c6bdcc9 = []byte{
	// 381 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x51, 0xc1, 0x4e, 0xea, 0x40,
	0x14, 0x6d, 0xe1, 0x3d, 0x02, 0x03, 0x2f, 0x2f, 0x29, 0x18, 0x91, 0x48, 0x87, 0x74, 0x63, 0x13,
	0x63, 0x1b, 0x70, 0xc7, 0xc6, 0xa4, 0xc6, 0x18, 0x36, 0xc6, 0xd4, 0xb8, 0x71, 0x43, 0x86, 0x76,
	0xac, 0x13, 0xda, 0x19, 0xc2, 0x8c, 0x46, 0xfe, 0xc0, 0xa5, 0x4b, 0xdd, 0xf1, 0x39, 0x2c, 0x59,
	0x1a, 0x17, 0x8d, 0x81, 0x8d, 0x6b, 0xbe, 0xc0, 0xb4, 0x53, 0x08, 0x31, 0x61, 0xd5, 0xde, 0x39,
	0xe7, 0x9e, 0x7b, 0xee, 0x3d, 0xa0, 0xe9, 0xdf, 0x13, 0x8a, 0xa8, 0x87, 0x6d, 0x2e, 0xd0, 0x10,
	0x8f, 0xed, 0x00, 0x53, 0xcc, 0x09, 0xb7, 0x46, 0x63, 0x26, 0x98, 0xb6, 0xbf, 0x86, 0x2d, 0x09,
	0x5b, 0x4f, 0xed, 0x01, 0x16, 0xa8, 0xdd, 0xa8, 0x05, 0x2c, 0x60, 0x29, 0xc7, 0x4e, 0xfe, 0x24,
	0xbd, 0x71, 0xe0, 0x31, 0x1e, 0x31, 0xde, 0x97, 0x80, 0x2c, 0x32, 0xe8, 0xf0, 0xf7, 0xa0, 0x4c,
	0x30, 0x45, 0x8d, 0xf7, 0x1c, 0xa8, 0x5c, 0xca, 0xc9, 0x37, 0x02, 0x09, 0xac, 0x5d, 0x81, 0xc2,
	0x08, 0x8d, 0x51, 0xc4, 0xeb, 0x6a, 0x4b, 0x35, 0xcb, 0x1d, 0x68, 0xed, 0x70, 0x62, 0x5d, 0xa7,
	0x34, 0x67, 0x6f, 0x16, 0x43, 0x65, 0x15, 0xc3, 0x7f, 0x13, 0x14, 0x85, 0x5d, 0x43, 0x36, 0x1b,
	0x6e, 0xa6, 0xa2, 0xf9, 0xa0, 0x12, 0x22, 0x2e, 0xfa, 0x1e, 0x0a, 0xc3, 0x3e, 0xf1, 0xeb, 0xb9,
	0x96, 0x6a, 0x96, 0x1c, 0xe7, 0x33, 0x86, 0x47, 0x01, 0x11, 0x0f, 0x8f, 0x03, 0xcb, 0x63, 0x51,
	0xe6, 0x38, 0xfb, 0x9c, 0x70, 0x7f, 0x68, 0x8b, 0xc9, 0x08, 0x73, 0xeb, 0x96, 0x50, 0xb1, 0x8a,
	0x61, 0x55, 0x6a, 0x6f, 0x0b, 0x19, 0x2e, 0x48, 0xca, 0x73, 0x14, 0x86, 0x3d, 0x5f, 0xeb, 0x81,
	0xbf, 0xc9, 0x3b, 0xaf, 0xe7, 0x5b, 0x79, 0xb3, 0xdc, 0x69, 0xee, 0x34, 0x9d, 0xf0, 0x9d, 0x5a,
	0x66, 0xb9, 0x22, 0x65, 0xd3, 0x4e, 0xc3, 0x95, 0x0a, 0xdd, 0xe2, 0xcb, 0x14, 0x2a, 0xdf, 0x53,
	0xa8, 0x18, 0x67, 0xa0, 0x20, 0x77, 0xd4, 0x6c, 0x50, 0xa4, 0x2c, 0x22, 0x14, 0xe3, 0xe4, 0x2c,
	0x79, 0xb3, 0xe4, 0x54, 0x57, 0x31, 0xfc, 0x2f, 0xdb, 0xd7, 0x88, 0xe1, 0x6e, 0x48, 0xdd, 0x3f,
	0x6f, 0x53, 0xa8, 0x38, 0x17, 0xb3, 0x85, 0xae, 0xce, 0x17, 0xba, 0xfa, 0xb5, 0xd0, 0xd5, 0xd7,
	0xa5, 0xae, 0xcc, 0x97, 0xba, 0xf2, 0xb1, 0xd4, 0x95, 0xbb, 0xe3, 0xad, 0xdd, 0x37, 0xf9, 0xf8,
	0x5c, 0x20, 0x41, 0x18, 0xb5, 0x9f, 0xd7, 0x51, 0xa5, 0x47, 0x18, 0x14, 0xd2, 0xa8, 0x4e, 0x7f,
	0x02, 0x00, 0x00, 0xff, 0xff, 0x4f, 0x9f, 0x3b, 0x42, 0x33, 0x02, 0x00, 0x00,
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Calls) > 0 {
		for iNdEx := len(m.Calls) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Calls[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if m.LastCallId != nil {
		{
			size := m.LastCallId.Size()
			i -= size
			if _, err := m.LastCallId.MarshalTo(dAtA[i:]); err != nil {
				return 0, err
			}
			i = encodeVarintGenesis(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Nominees) > 0 {
		for iNdEx := len(m.Nominees) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Nominees[iNdEx])
			copy(dAtA[i:], m.Nominees[iNdEx])
			i = encodeVarintGenesis(dAtA, i, uint64(len(m.Nominees[iNdEx])))
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintGenesis(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenesis(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovGenesis(uint64(l))
	if m.LastCallId != nil {
		l = m.LastCallId.Size()
		n += 1 + l + sovGenesis(uint64(l))
	}
	if len(m.Calls) > 0 {
		for _, e := range m.Calls {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	return n
}

func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Nominees) > 0 {
		for _, s := range m.Nominees {
			l = len(s)
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	return n
}

func sovGenesis(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenesis(x uint64) (n int) {
	return sovGenesis(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastCallId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			var v github_com_cosmos_cosmos_sdk_types.Uint
			m.LastCallId = &v
			if err := m.LastCallId.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Calls", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Calls = append(m.Calls, Call{})
			if err := m.Calls[len(m.Calls)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Nominees", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Nominees = append(m.Nominees, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenesis(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenesis
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenesis
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenesis
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenesis        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenesis          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenesis = fmt.Errorf("proto: unexpected end of group")
)
