// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: dfinance/vm/genesis.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/codec/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	_ "github.com/regen-network/cosmos-proto"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type GenesisState struct {
	WriteSet []GenesisState_WriteOp `protobuf:"bytes,1,rep,name=write_set,json=writeSet,proto3" json:"write_set" yaml:"write_set"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_6fec33bf450a5340, []int{0}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

type GenesisState_WriteOp struct {
	// Move address (HEX string)
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty" yaml:"address"`
	// Move module path (HEX string)
	Path string `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty" yaml:"path"`
	// Module code (HEX string)
	Value string `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty" yaml:"value"`
}

func (m *GenesisState_WriteOp) Reset()      { *m = GenesisState_WriteOp{} }
func (*GenesisState_WriteOp) ProtoMessage() {}
func (*GenesisState_WriteOp) Descriptor() ([]byte, []int) {
	return fileDescriptor_6fec33bf450a5340, []int{0, 0}
}
func (m *GenesisState_WriteOp) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState_WriteOp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState_WriteOp.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState_WriteOp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState_WriteOp.Merge(m, src)
}
func (m *GenesisState_WriteOp) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState_WriteOp) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState_WriteOp.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState_WriteOp proto.InternalMessageInfo

func init() {
	proto.RegisterType((*GenesisState)(nil), "dfinance.vm.v1beta1.GenesisState")
	proto.RegisterType((*GenesisState_WriteOp)(nil), "dfinance.vm.v1beta1.GenesisState.WriteOp")
}

func init() { proto.RegisterFile("dfinance/vm/genesis.proto", fileDescriptor_6fec33bf450a5340) }

var fileDescriptor_6fec33bf450a5340 = []byte{
	// 365 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0x31, 0x4f, 0xf2, 0x40,
	0x18, 0xc7, 0x5b, 0x78, 0x5f, 0x81, 0x42, 0x94, 0x54, 0x87, 0xc2, 0xd0, 0x23, 0x35, 0x51, 0x4c,
	0x4c, 0x1b, 0x74, 0x63, 0x93, 0xc5, 0xd1, 0xa4, 0x0c, 0x26, 0x2e, 0x78, 0xa5, 0x47, 0x69, 0x42,
	0x7b, 0x0d, 0xf7, 0x50, 0xe5, 0x1b, 0xb0, 0x69, 0x9c, 0x1c, 0xf9, 0x38, 0x8c, 0x8c, 0x4e, 0x8d,
	0x81, 0xc5, 0xb9, 0x9f, 0xc0, 0xf4, 0xae, 0x10, 0x63, 0xdc, 0xfe, 0x7d, 0x7e, 0xbf, 0x7f, 0xf3,
	0xe4, 0x1e, 0xa5, 0xe1, 0x8e, 0xfc, 0x10, 0x87, 0x43, 0x62, 0xc5, 0x81, 0xe5, 0x91, 0x90, 0x30,
	0x9f, 0x99, 0xd1, 0x94, 0x02, 0x55, 0x8f, 0x77, 0xc8, 0x8c, 0x03, 0x33, 0xee, 0x38, 0x04, 0x70,
	0xa7, 0xd9, 0xf0, 0x28, 0xf5, 0x26, 0xc4, 0xe2, 0x8a, 0x33, 0x1b, 0x59, 0x38, 0x9c, 0x0b, 0xbf,
	0x89, 0x7e, 0x23, 0xf0, 0x03, 0xc2, 0x00, 0x07, 0x51, 0x2e, 0x9c, 0x78, 0xd4, 0xa3, 0x3c, 0x5a,
	0x59, 0xca, 0xa7, 0x8d, 0x21, 0x65, 0x01, 0x65, 0x03, 0x01, 0xc4, 0x87, 0x40, 0xc6, 0x4b, 0x41,
	0xa9, 0xdd, 0x8a, 0x9d, 0xfa, 0x80, 0x81, 0xa8, 0x8f, 0x4a, 0xe5, 0x69, 0xea, 0x03, 0x19, 0x30,
	0x02, 0x9a, 0xdc, 0x2a, 0xb6, 0xab, 0x57, 0x17, 0xe6, 0x1f, 0x6b, 0x9a, 0x3f, 0x5b, 0xe6, 0x7d,
	0x56, 0xb9, 0x8b, 0x7a, 0xda, 0x2a, 0x41, 0x52, 0x9a, 0xa0, 0xfa, 0x1c, 0x07, 0x93, 0xae, 0xb1,
	0xff, 0x93, 0x61, 0x97, 0x79, 0xee, 0x13, 0x68, 0xbe, 0xc9, 0x4a, 0x29, 0xf7, 0xd5, 0x4b, 0xa5,
	0x84, 0x5d, 0x77, 0x4a, 0x18, 0xd3, 0xe4, 0x96, 0xdc, 0xae, 0xf4, 0xd4, 0x34, 0x41, 0x87, 0xa2,
	0x9c, 0x03, 0xc3, 0xde, 0x29, 0xea, 0xa9, 0xf2, 0x2f, 0xc2, 0x30, 0xd6, 0x0a, 0x5c, 0x3d, 0x4a,
	0x13, 0x54, 0x15, 0x6a, 0x36, 0x35, 0x6c, 0x0e, 0xd5, 0x33, 0xe5, 0x7f, 0x8c, 0x27, 0x33, 0xa2,
	0x15, 0xb9, 0x55, 0x4f, 0x13, 0x54, 0x13, 0x16, 0x1f, 0x1b, 0xb6, 0xc0, 0xdd, 0xda, 0x62, 0x89,
	0xa4, 0xf7, 0x25, 0x92, 0xbe, 0x96, 0x48, 0xea, 0x96, 0x17, 0x79, 0xea, 0xdd, 0xac, 0x36, 0xba,
	0xbc, 0xde, 0xe8, 0xf2, 0xe7, 0x46, 0x97, 0x5f, 0xb7, 0xba, 0xb4, 0xde, 0xea, 0xd2, 0xc7, 0x56,
	0x97, 0x1e, 0xce, 0x3d, 0x1f, 0xc6, 0x33, 0xc7, 0x1c, 0xd2, 0xc0, 0xda, 0xdf, 0xd4, 0x65, 0x80,
	0xc1, 0xa7, 0xa1, 0xf5, 0x9c, 0x9d, 0x17, 0xe6, 0x11, 0x61, 0xce, 0x01, 0x7f, 0xdb, 0xeb, 0xef,
	0x00, 0x00, 0x00, 0xff, 0xff, 0xd0, 0xf9, 0xeb, 0x33, 0xfa, 0x01, 0x00, 0x00,
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.WriteSet) > 0 {
		for iNdEx := len(m.WriteSet) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.WriteSet[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *GenesisState_WriteOp) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState_WriteOp) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState_WriteOp) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Value) > 0 {
		i -= len(m.Value)
		copy(dAtA[i:], m.Value)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.Value)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Path) > 0 {
		i -= len(m.Path)
		copy(dAtA[i:], m.Path)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.Path)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintGenesis(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenesis(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.WriteSet) > 0 {
		for _, e := range m.WriteSet {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	return n
}

func (m *GenesisState_WriteOp) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	l = len(m.Path)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	l = len(m.Value)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	return n
}

func sovGenesis(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenesis(x uint64) (n int) {
	return sovGenesis(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field WriteSet", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.WriteSet = append(m.WriteSet, GenesisState_WriteOp{})
			if err := m.WriteSet[len(m.WriteSet)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GenesisState_WriteOp) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: WriteOp: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: WriteOp: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Path", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Path = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Value", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Value = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenesis(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenesis
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenesis
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenesis
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenesis        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenesis          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenesis = fmt.Errorf("proto: unexpected end of group")
)
