// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: dfinance/namespace/query.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "github.com/regen-network/cosmos-proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// DomainsAccountRequest is request type for Query/BuyName RPC method.
type DomainsAccountRequest struct {
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty" yaml:"address"`
}

func (m *DomainsAccountRequest) Reset()         { *m = DomainsAccountRequest{} }
func (m *DomainsAccountRequest) String() string { return proto.CompactTextString(m) }
func (*DomainsAccountRequest) ProtoMessage()    {}
func (*DomainsAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d015dde39ad0b661, []int{0}
}
func (m *DomainsAccountRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *DomainsAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_DomainsAccountRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *DomainsAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DomainsAccountRequest.Merge(m, src)
}
func (m *DomainsAccountRequest) XXX_Size() int {
	return m.Size()
}
func (m *DomainsAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DomainsAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DomainsAccountRequest proto.InternalMessageInfo

func (m *DomainsAccountRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

// DomainsAccountResponse is response type for Query/BuyName RPC method.
type DomainsAccountResponse struct {
	Whois []Whois `protobuf:"bytes,1,rep,name=whois,proto3" json:"whois" yaml:"whois"`
}

func (m *DomainsAccountResponse) Reset()         { *m = DomainsAccountResponse{} }
func (m *DomainsAccountResponse) String() string { return proto.CompactTextString(m) }
func (*DomainsAccountResponse) ProtoMessage()    {}
func (*DomainsAccountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d015dde39ad0b661, []int{1}
}
func (m *DomainsAccountResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *DomainsAccountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_DomainsAccountResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *DomainsAccountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DomainsAccountResponse.Merge(m, src)
}
func (m *DomainsAccountResponse) XXX_Size() int {
	return m.Size()
}
func (m *DomainsAccountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DomainsAccountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DomainsAccountResponse proto.InternalMessageInfo

func (m *DomainsAccountResponse) GetWhois() []Whois {
	if m != nil {
		return m.Whois
	}
	return nil
}

func init() {
	proto.RegisterType((*DomainsAccountRequest)(nil), "dfinance.namespace.v1beta1.DomainsAccountRequest")
	proto.RegisterType((*DomainsAccountResponse)(nil), "dfinance.namespace.v1beta1.DomainsAccountResponse")
}

func init() { proto.RegisterFile("dfinance/namespace/query.proto", fileDescriptor_d015dde39ad0b661) }

var fileDescriptor_d015dde39ad0b661 = []byte{
	// 371 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x91, 0xcf, 0x4a, 0xeb, 0x40,
	0x14, 0xc6, 0x93, 0x7b, 0xe9, 0xbd, 0xdc, 0x5c, 0xe9, 0x22, 0x54, 0xd1, 0x20, 0x53, 0x1d, 0x5c,
	0x14, 0x91, 0x0c, 0xad, 0x3b, 0x77, 0x16, 0x05, 0x37, 0x2e, 0xec, 0x46, 0x70, 0x23, 0x93, 0x64,
	0x4c, 0x03, 0xcd, 0x9c, 0x34, 0x67, 0xa2, 0x76, 0xeb, 0x13, 0x08, 0x3e, 0x82, 0x6b, 0xdf, 0xa3,
	0xcb, 0x82, 0x1b, 0x57, 0x45, 0x5a, 0x9f, 0xa0, 0x4f, 0x20, 0xe9, 0xa4, 0x56, 0xa5, 0x0a, 0xee,
	0x66, 0xf8, 0xbe, 0xef, 0x77, 0xfe, 0x59, 0x24, 0xb8, 0x88, 0x24, 0x97, 0xbe, 0x60, 0x92, 0xc7,
	0x02, 0x13, 0xee, 0x0b, 0xd6, 0xcd, 0x44, 0xda, 0x73, 0x93, 0x14, 0x14, 0xd8, 0xce, 0x4c, 0x77,
	0xdf, 0x74, 0xf7, 0xb2, 0xee, 0x09, 0xc5, 0xeb, 0x4e, 0x25, 0x84, 0x10, 0xa6, 0x36, 0x96, 0xbf,
	0x74, 0xc2, 0x59, 0x0f, 0x01, 0xc2, 0x8e, 0x60, 0x3c, 0x89, 0x18, 0x97, 0x12, 0x14, 0x57, 0x11,
	0x48, 0x2c, 0xd4, 0x35, 0x1f, 0x30, 0x06, 0x3c, 0xd7, 0x31, 0xfd, 0x29, 0x24, 0xba, 0xa0, 0x95,
	0x79, 0x51, 0xed, 0x21, 0x3a, 0xc1, 0x3c, 0x8e, 0x82, 0x15, 0x7d, 0x30, 0x1f, 0x22, 0xa9, 0x75,
	0x7a, 0x68, 0x2d, 0x1f, 0x40, 0xcc, 0x23, 0x89, 0xfb, 0xbe, 0x0f, 0x99, 0x54, 0x2d, 0xd1, 0xcd,
	0x04, 0x2a, 0x7b, 0xc7, 0xfa, 0xcb, 0x83, 0x20, 0x15, 0x88, 0xab, 0xe6, 0x86, 0x59, 0xfb, 0xd7,
	0xb4, 0x27, 0xc3, 0x6a, 0xb9, 0xc7, 0xe3, 0xce, 0x1e, 0x2d, 0x04, 0xda, 0x9a, 0x59, 0x68, 0x68,
	0xad, 0x7c, 0xc6, 0x60, 0x02, 0x12, 0x85, 0x7d, 0x6c, 0x95, 0xae, 0xda, 0x10, 0xe5, 0x94, 0xdf,
	0xb5, 0xff, 0x8d, 0x4d, 0xf7, 0xeb, 0xfd, 0xb8, 0xa7, 0xb9, 0xb1, 0x59, 0xe9, 0x0f, 0xab, 0xc6,
	0x64, 0x58, 0x5d, 0xd2, 0xc5, 0xa6, 0x69, 0xda, 0xd2, 0x94, 0xc6, 0x83, 0x69, 0x95, 0x4e, 0xf2,
	0x75, 0xdb, 0xf7, 0xa6, 0x55, 0xfe, 0x58, 0xd3, 0xae, 0x7f, 0x07, 0x5f, 0x38, 0xa6, 0xd3, 0xf8,
	0x49, 0x44, 0x8f, 0x44, 0xb7, 0x6f, 0x1e, 0x5f, 0xee, 0x7e, 0x6d, 0x51, 0xca, 0x16, 0x1c, 0x60,
	0xb6, 0xe3, 0x84, 0xa7, 0x3c, 0xc6, 0xe6, 0x51, 0x7f, 0x44, 0xcc, 0xc1, 0x88, 0x98, 0xcf, 0x23,
	0x62, 0xde, 0x8e, 0x89, 0x31, 0x18, 0x13, 0xe3, 0x69, 0x4c, 0x8c, 0x33, 0x37, 0x8c, 0x54, 0x3b,
	0xf3, 0x5c, 0x1f, 0xe2, 0x39, 0x27, 0x40, 0x7d, 0x7d, 0x76, 0xfd, 0x0e, 0xa9, 0x7a, 0x89, 0x40,
	0xef, 0xcf, 0xf4, 0x60, 0xbb, 0xaf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x61, 0xd1, 0x0d, 0x7c, 0x81,
	0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	DomainsAccount(ctx context.Context, in *DomainsAccountRequest, opts ...grpc.CallOption) (*DomainsAccountResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) DomainsAccount(ctx context.Context, in *DomainsAccountRequest, opts ...grpc.CallOption) (*DomainsAccountResponse, error) {
	out := new(DomainsAccountResponse)
	err := c.cc.Invoke(ctx, "/dfinance.namespace.v1beta1.Query/DomainsAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	DomainsAccount(context.Context, *DomainsAccountRequest) (*DomainsAccountResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) DomainsAccount(ctx context.Context, req *DomainsAccountRequest) (*DomainsAccountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DomainsAccount not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_DomainsAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DomainsAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).DomainsAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dfinance.namespace.v1beta1.Query/DomainsAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).DomainsAccount(ctx, req.(*DomainsAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "dfinance.namespace.v1beta1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DomainsAccount",
			Handler:    _Query_DomainsAccount_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dfinance/namespace/query.proto",
}

func (m *DomainsAccountRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DomainsAccountRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *DomainsAccountRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *DomainsAccountResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DomainsAccountResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *DomainsAccountResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Whois) > 0 {
		for iNdEx := len(m.Whois) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Whois[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *DomainsAccountRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *DomainsAccountResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Whois) > 0 {
		for _, e := range m.Whois {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *DomainsAccountRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DomainsAccountRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DomainsAccountRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *DomainsAccountResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DomainsAccountResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DomainsAccountResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Whois", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Whois = append(m.Whois, Whois{})
			if err := m.Whois[len(m.Whois)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
