// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: dfinance/oracle/genesis.proto

package types

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	_ "github.com/regen-network/cosmos-proto"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type GenesisState struct {
	Params        Params         `protobuf:"bytes,1,opt,name=params,proto3" json:"params" yaml:"params"`
	Oracles       []Oracle       `protobuf:"bytes,2,rep,name=oracles,proto3" json:"oracles" yaml:"oracles"`
	Assets        []Asset        `protobuf:"bytes,3,rep,name=assets,proto3" json:"assets" yaml:"assets"`
	CurrentPrices []CurrentPrice `protobuf:"bytes,4,rep,name=current_prices,json=currentPrices,proto3" json:"current_prices" yaml:"current_prices"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_648e9c4bb5a710a2, []int{0}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

// Params keeps keeper parameters (which might be changed via Gov).
type Params struct {
	// Admin account addresses
	Nominees  []string               `protobuf:"bytes,1,rep,name=nominees,proto3" json:"nominees,omitempty" yaml:"nominees"`
	PostPrice Params_PostPriceParams `protobuf:"bytes,2,opt,name=post_price,json=postPrice,proto3" json:"post_price" yaml:"post_price"`
}

func (m *Params) Reset()      { *m = Params{} }
func (*Params) ProtoMessage() {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_648e9c4bb5a710a2, []int{1}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetNominees() []string {
	if m != nil {
		return m.Nominees
	}
	return nil
}

func (m *Params) GetPostPrice() Params_PostPriceParams {
	if m != nil {
		return m.PostPrice
	}
	return Params_PostPriceParams{}
}

// PostPriceParams keeps price posting parameters.
type Params_PostPriceParams struct {
	ReceivedAtDiffInS uint32 `protobuf:"varint,1,opt,name=received_at_diff_in_s,json=receivedAtDiffInS,proto3" json:"received_at_diff_in_s,omitempty" yaml:"received_at_diff_in_s"`
}

func (m *Params_PostPriceParams) Reset()         { *m = Params_PostPriceParams{} }
func (m *Params_PostPriceParams) String() string { return proto.CompactTextString(m) }
func (*Params_PostPriceParams) ProtoMessage()    {}
func (*Params_PostPriceParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_648e9c4bb5a710a2, []int{1, 0}
}
func (m *Params_PostPriceParams) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params_PostPriceParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params_PostPriceParams.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params_PostPriceParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params_PostPriceParams.Merge(m, src)
}
func (m *Params_PostPriceParams) XXX_Size() int {
	return m.Size()
}
func (m *Params_PostPriceParams) XXX_DiscardUnknown() {
	xxx_messageInfo_Params_PostPriceParams.DiscardUnknown(m)
}

var xxx_messageInfo_Params_PostPriceParams proto.InternalMessageInfo

func (m *Params_PostPriceParams) GetReceivedAtDiffInS() uint32 {
	if m != nil {
		return m.ReceivedAtDiffInS
	}
	return 0
}

func init() {
	proto.RegisterType((*GenesisState)(nil), "dfinance.oracle.v1beta1.GenesisState")
	proto.RegisterType((*Params)(nil), "dfinance.oracle.v1beta1.Params")
	proto.RegisterType((*Params_PostPriceParams)(nil), "dfinance.oracle.v1beta1.Params.PostPriceParams")
}

func init() { proto.RegisterFile("dfinance/oracle/genesis.proto", fileDescriptor_648e9c4bb5a710a2) }

var fileDescriptor_648e9c4bb5a710a2 = []byte{
	// 489 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0x31, 0x6f, 0xd3, 0x40,
	0x14, 0xc7, 0xed, 0xa4, 0x0a, 0xed, 0x41, 0x5a, 0xd5, 0x10, 0x70, 0xa3, 0xd6, 0x8e, 0x4e, 0x42,
	0xaa, 0x84, 0x64, 0xab, 0xb0, 0x65, 0xab, 0x01, 0x21, 0x06, 0x20, 0xb8, 0x1b, 0x8b, 0x75, 0x71,
	0x9e, 0xcd, 0x89, 0xf8, 0xce, 0xf2, 0x5d, 0x2a, 0xfa, 0x0d, 0x18, 0x61, 0x63, 0xcc, 0xc7, 0xe9,
	0xd8, 0x91, 0x29, 0x42, 0xc9, 0xc2, 0x9c, 0x85, 0x15, 0xe5, 0xee, 0x1c, 0x41, 0x44, 0x60, 0xf3,
	0xf9, 0xfd, 0xde, 0xef, 0xfe, 0xba, 0xf7, 0xd0, 0xc9, 0x28, 0xa3, 0x8c, 0xb0, 0x14, 0x42, 0x5e,
	0x91, 0x74, 0x0c, 0x61, 0x0e, 0x0c, 0x04, 0x15, 0x41, 0x59, 0x71, 0xc9, 0x9d, 0x07, 0x75, 0x39,
	0xd0, 0xe5, 0xe0, 0xf2, 0x6c, 0x08, 0x92, 0x9c, 0x75, 0xef, 0xe5, 0x3c, 0xe7, 0x8a, 0x09, 0x57,
	0x5f, 0x1a, 0xef, 0xfa, 0x39, 0xe7, 0xf9, 0x18, 0x42, 0x75, 0x1a, 0x4e, 0xb2, 0x50, 0xd2, 0x02,
	0x84, 0x24, 0x45, 0x69, 0x80, 0xa3, 0x94, 0x8b, 0x82, 0x8b, 0x44, 0x77, 0xea, 0x83, 0x29, 0x1d,
	0x6f, 0x26, 0x31, 0x37, 0xaa, 0x2a, 0xfe, 0xd9, 0x40, 0x77, 0x5e, 0xe8, 0x68, 0x17, 0x92, 0x48,
	0x70, 0x5e, 0xa3, 0x56, 0x49, 0x2a, 0x52, 0x08, 0xd7, 0xee, 0xd9, 0xa7, 0xb7, 0x1f, 0xfb, 0xc1,
	0x96, 0xa8, 0xc1, 0x40, 0x61, 0x51, 0xe7, 0x7a, 0xe6, 0x5b, 0xcb, 0x99, 0xdf, 0xbe, 0x22, 0xc5,
	0xb8, 0x8f, 0x75, 0x33, 0x8e, 0x8d, 0xc5, 0x79, 0x8b, 0x6e, 0xe9, 0x3e, 0xe1, 0x36, 0x7a, 0xcd,
	0x7f, 0x0a, 0xdf, 0xa8, 0x63, 0x74, 0xdf, 0x08, 0xf7, 0xb5, 0xd0, 0x74, 0xe3, 0xb8, 0xf6, 0x38,
	0xaf, 0x50, 0x8b, 0x08, 0x01, 0x52, 0xb8, 0x4d, 0x65, 0xf4, 0xb6, 0x1a, 0xcf, 0x57, 0xd8, 0x66,
	0x42, 0xdd, 0x8b, 0x63, 0x23, 0x71, 0x3e, 0xa0, 0xfd, 0x74, 0x52, 0x55, 0xc0, 0x64, 0x52, 0x56,
	0x34, 0x05, 0xe1, 0xee, 0x28, 0xed, 0xc3, 0xad, 0xda, 0xa7, 0x1a, 0x1f, 0xac, 0xe8, 0xe8, 0xc4,
	0xd8, 0x3b, 0xda, 0xfe, 0xa7, 0x0a, 0xc7, 0xed, 0xf4, 0x37, 0x58, 0xf4, 0x77, 0x3f, 0x4d, 0x7d,
	0xeb, 0xc7, 0xd4, 0xb7, 0xf0, 0x97, 0x06, 0x6a, 0xe9, 0x27, 0x74, 0x42, 0xb4, 0xcb, 0x78, 0x41,
	0x19, 0xc0, 0xea, 0xd5, 0x9b, 0xa7, 0x7b, 0xd1, 0xdd, 0xe5, 0xcc, 0x3f, 0xd0, 0xc2, 0xba, 0x82,
	0xe3, 0x35, 0xe4, 0x50, 0x84, 0x4a, 0x2e, 0xcc, 0x25, 0x6e, 0x43, 0x0d, 0x2a, 0xfc, 0xcf, 0xa0,
	0x82, 0x01, 0x17, 0x3a, 0x85, 0x19, 0xdc, 0x91, 0x09, 0x7e, 0x68, 0x06, 0xb7, 0x16, 0xe2, 0x78,
	0xaf, 0xac, 0xd9, 0x2e, 0xa0, 0x83, 0x8d, 0x46, 0x27, 0x46, 0x9d, 0x0a, 0x52, 0xa0, 0x97, 0x30,
	0x4a, 0x88, 0x4c, 0x46, 0x34, 0xcb, 0x12, 0xca, 0x12, 0xbd, 0x31, 0xed, 0xa8, 0xb7, 0x9c, 0xf9,
	0xc7, 0xda, 0xf9, 0x57, 0x0c, 0xc7, 0x87, 0xf5, 0xff, 0x73, 0xf9, 0x8c, 0x66, 0xd9, 0x4b, 0x76,
	0xd1, 0xdf, 0xf9, 0x3a, 0xf5, 0xad, 0xe8, 0xf9, 0xf5, 0xdc, 0xb3, 0x6f, 0xe6, 0x9e, 0xfd, 0x7d,
	0xee, 0xd9, 0x9f, 0x17, 0x9e, 0x75, 0xb3, 0xf0, 0xac, 0x6f, 0x0b, 0xcf, 0x7a, 0xf7, 0x28, 0xa7,
	0xf2, 0xfd, 0x64, 0x18, 0xa4, 0xbc, 0x08, 0xd7, 0x0b, 0x3d, 0x12, 0x92, 0x48, 0xca, 0x59, 0xf8,
	0xb1, 0xde, 0x6d, 0x79, 0x55, 0x82, 0x18, 0xb6, 0xd4, 0x6e, 0x3f, 0xf9, 0x15, 0x00, 0x00, 0xff,
	0xff, 0xdd, 0x81, 0x13, 0x4a, 0x85, 0x03, 0x00, 0x00,
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.CurrentPrices) > 0 {
		for iNdEx := len(m.CurrentPrices) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.CurrentPrices[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.Assets) > 0 {
		for iNdEx := len(m.Assets) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Assets[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.Oracles) > 0 {
		for iNdEx := len(m.Oracles) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Oracles[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.PostPrice.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.Nominees) > 0 {
		for iNdEx := len(m.Nominees) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Nominees[iNdEx])
			copy(dAtA[i:], m.Nominees[iNdEx])
			i = encodeVarintGenesis(dAtA, i, uint64(len(m.Nominees[iNdEx])))
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *Params_PostPriceParams) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params_PostPriceParams) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params_PostPriceParams) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ReceivedAtDiffInS != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.ReceivedAtDiffInS))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintGenesis(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenesis(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovGenesis(uint64(l))
	if len(m.Oracles) > 0 {
		for _, e := range m.Oracles {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.Assets) > 0 {
		for _, e := range m.Assets {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.CurrentPrices) > 0 {
		for _, e := range m.CurrentPrices {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	return n
}

func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Nominees) > 0 {
		for _, s := range m.Nominees {
			l = len(s)
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	l = m.PostPrice.Size()
	n += 1 + l + sovGenesis(uint64(l))
	return n
}

func (m *Params_PostPriceParams) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ReceivedAtDiffInS != 0 {
		n += 1 + sovGenesis(uint64(m.ReceivedAtDiffInS))
	}
	return n
}

func sovGenesis(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenesis(x uint64) (n int) {
	return sovGenesis(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Oracles", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Oracles = append(m.Oracles, Oracle{})
			if err := m.Oracles[len(m.Oracles)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Assets", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Assets = append(m.Assets, Asset{})
			if err := m.Assets[len(m.Assets)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CurrentPrices", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CurrentPrices = append(m.CurrentPrices, CurrentPrice{})
			if err := m.CurrentPrices[len(m.CurrentPrices)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Nominees", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Nominees = append(m.Nominees, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PostPrice", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.PostPrice.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Params_PostPriceParams) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PostPriceParams: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PostPriceParams: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReceivedAtDiffInS", wireType)
			}
			m.ReceivedAtDiffInS = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ReceivedAtDiffInS |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenesis(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenesis
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenesis
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenesis
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenesis        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenesis          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenesis = fmt.Errorf("proto: unexpected end of group")
)
